version: 3

vars:
  COVERAGE_FILE: coverage.out

tasks:
  # === INFORMATION ===
  default:
    desc: List all available tasks
    cmds:
      - task --list

  # === CODE GENERATION ===
  proto:
    desc: Generate gRPC protobuf code for scout service
    cmds:
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative grpc/proto/scout.proto
      - cmd: move grpc\proto\scout.pb.go grpc\scoutpb\scout.pb.go
        platforms: [ windows ]
      - cmd: move grpc\proto\scout_grpc.pb.go grpc\scoutpb\scout_grpc.pb.go
        platforms: [ windows ]
      - cmd: mv grpc/proto/scout.pb.go grpc/scoutpb/scout.pb.go
        platforms: [ linux, darwin ]
      - cmd: mv grpc/proto/scout_grpc.pb.go grpc/scoutpb/scout_grpc.pb.go
        platforms: [ linux, darwin ]
    sources:
      - grpc/proto/*.proto
    generates:
      - grpc/scoutpb/*.pb.go

  # === BUILD ===
  build:
    desc: Build the scout CLI binary
    cmds:
      - go build -o bin/scout ./cmd/scout

  # === TEST TASKS ===
  test:
    desc: Run all tests with coverage
    cmds:
      - go test -v -race -coverprofile={{.COVERAGE_FILE}} ./pkg/scout/... ./scraper/... ./grpc/...

  test:coverage:
    desc: Generate HTML coverage report
    deps: [ test ]
    cmds:
      - go tool cover -html={{.COVERAGE_FILE}} -o coverage.html
      - echo "Coverage report generated at coverage.html"

  test:cover:
    desc: Run tests and show coverage percentage
    cmds:
      - go test -coverprofile={{.COVERAGE_FILE}} ./pkg/scout/... ./scraper/... ./grpc/...
      - cmd: go tool cover -func={{.COVERAGE_FILE}} | findstr "total:"
        platforms: [ windows ]
      - cmd: go tool cover -func={{.COVERAGE_FILE}} | grep "total:"
        platforms: [ linux, darwin ]

  test:unit:
    desc: Run unit tests only (skip integration)
    cmds:
      - go test -v -short ./pkg/scout/... ./scraper/... ./grpc/...

  # === CODE QUALITY ===
  fmt:
    desc: Format all Go code
    cmds:
      - go fmt ./...
      - goimports -w .

  vet:
    desc: Run go vet static analysis
    cmds:
      - go vet ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run ./...

  lint:fix:
    desc: Run linter and auto-fix issues
    cmds:
      - golangci-lint run --fix ./...

  check:
    desc: Run all quality checks (fmt, vet, lint, test)
    cmds:
      - task: fmt
      - task: vet
      - task: lint
      - task: test

  # === gRPC TASKS ===
  grpc:server:
    desc: Run the gRPC scout server
    cmds:
      - go run ./cmd/scout server {{.CLI_ARGS}}

  grpc:client:
    desc: Run the interactive gRPC client
    cmds:
      - go run ./cmd/scout client {{.CLI_ARGS}}

  # === DEPENDENCY MANAGEMENT ===
  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy
      - go mod verify

  deps:upgrade:
    desc: Upgrade all dependencies to latest versions
    cmds:
      - go get -u ./...
      - go mod tidy
      - go mod verify

  # === CLEANUP ===
  clean:
    desc: Clean build artifacts and generated files
    cmds:
      - cmd: rm -rf bin
        platforms: [ linux, darwin ]
      - cmd: rd /s /q bin 2>nul
        platforms: [ windows ]
        ignore_error: true
      - rm -f {{.COVERAGE_FILE}} coverage.html
