apiVersion: v2
name: scout
description: Scout browser automation service for Kubernetes
version: 0.2.1
appVersion: "1.1.1"
type: application
keywords:
  - browser
  - automation
  - scraping
  - chrome
maintainers:
  - name: inovacc
    url: https://github.com/inovacc
