// This file contains the methods that panics when error return value is not nil.
// Their function names are all prefixed with Must.
// A function here is usually a wrapper for the error version with fixed default options to make it easier to use.
//
// For example the source code of [Element.Click] and [Element.MustClick]. MustClick has no argument.
// But `Click` has a `button` argument to decide which button to click.
// `MustClick` feels like a version of `Click` with some default behaviors.

package engine

import (
	"errors"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/inovacc/scout/internal/engine/lib/devices"
	"github.com/inovacc/scout/internal/engine/lib/input"
	proto2 "github.com/inovacc/scout/internal/engine/lib/proto"
	"github.com/inovacc/scout/internal/engine/lib/utils"
	"github.com/ysmood/gson"
)

// It must be generated by genE.
type eFunc func(args ...any)

// Generate a eFunc with the specified fail function.
// If the last arg of eFunc is error the fail will be called.
func genE(fail func(any)) eFunc {
	return func(args ...any) {
		err, ok := args[len(args)-1].(error)
		if ok {
			fail(err)
		}
	}
}

// WithPanic returns a browser clone with the specified panic function.
// The fail must stop the current goroutine's execution immediately, such as use [runtime.Goexit] or panic inside it.
func (b *rodBrowser) WithPanic(fail func(any)) *rodBrowser {
	n := *b
	n.e = genE(fail)

	return &n
}

// MustConnect is similar to [Browser.Connect].
func (b *rodBrowser) MustConnect() *rodBrowser {
	b.e(b.Connect())
	return b
}

// MustClose is similar to [Browser.Close].
func (b *rodBrowser) MustClose() {
	_ = b.Close()
}

// MustIncognito is similar to [Browser.Incognito].
func (b *rodBrowser) MustIncognito() *rodBrowser {
	p, err := b.Incognito()
	b.e(err)

	return p
}

// MustPage is similar to [Browser.Page].
// The url list will be joined by "/".
func (b *rodBrowser) MustPage(url ...string) *rodPage {
	p, err := b.Page(proto2.TargetCreateTarget{URL: strings.Join(url, "/")})
	b.e(err)

	return p
}

// MustPages is similar to [Browser.Pages].
func (b *rodBrowser) MustPages() Pages {
	list, err := b.Pages()
	b.e(err)

	return list
}

// MustPageFromTargetID is similar to [Browser.PageFromTargetID].
func (b *rodBrowser) MustPageFromTargetID(targetID proto2.TargetTargetID) *rodPage {
	p, err := b.PageFromTarget(targetID)
	b.e(err)

	return p
}

// MustHandleAuth is similar to [Browser.HandleAuth].
func (b *rodBrowser) MustHandleAuth(username, password string) (wait func()) {
	w := b.HandleAuth(username, password)
	return func() { b.e(w()) }
}

// MustIgnoreCertErrors is similar to [Browser.IgnoreCertErrors].
func (b *rodBrowser) MustIgnoreCertErrors(enable bool) *rodBrowser {
	b.e(b.IgnoreCertErrors(enable))
	return b
}

// MustGetCookies is similar to [Browser.GetCookies].
func (b *rodBrowser) MustGetCookies() []*proto2.NetworkCookie {
	nc, err := b.GetCookies()
	b.e(err)

	return nc
}

// MustSetCookies is similar to [Browser.SetCookies].
// If the len(cookies) is 0 it will clear all the cookies.
func (b *rodBrowser) MustSetCookies(cookies ...*proto2.NetworkCookie) *rodBrowser {
	if len(cookies) == 0 {
		b.e(b.SetCookies(nil))
	} else {
		b.e(b.SetCookies(proto2.CookiesToParams(cookies)))
	}

	return b
}

// MustWaitDownload is similar to [Browser.WaitDownload].
// It will read the file into bytes then remove the file.
func (b *rodBrowser) MustWaitDownload() func() []byte {
	tmpDir := filepath.Join(os.TempDir(), "rod", "downloads")
	wait := b.WaitDownload(tmpDir)

	return func() []byte {
		info := wait()
		path := filepath.Join(tmpDir, info.GUID)

		defer func() { _ = os.Remove(path) }()

		data, err := os.ReadFile(path)
		b.e(err)

		return data
	}
}

// MustVersion is similar to [Browser.Version].
func (b *rodBrowser) MustVersion() *proto2.BrowserGetVersionResult {
	v, err := b.Version()
	b.e(err)

	return v
}

// MustFind is similar to [Browser.Find].
func (ps Pages) MustFind(selector string) *rodPage {
	p, err := ps.Find(selector)
	if err != nil {
		if len(ps) > 0 {
			ps[0].e(err)
		} else {
			// fallback to utils.E, because we don't have enough
			// context to call the scope `.e`.
			utils.E(err)
		}
	}

	return p
}

// MustFindByURL is similar to [Page.FindByURL].
func (ps Pages) MustFindByURL(regex string) *rodPage {
	p, err := ps.FindByURL(regex)
	if err != nil {
		if len(ps) > 0 {
			ps[0].e(err)
		} else {
			// fallback to utils.E, because we don't have enough
			// context to call the scope `.e`.
			utils.E(err)
		}
	}

	return p
}

// WithPanic returns a page clone with the specified panic function.
// The fail must stop the current goroutine's execution immediately, such as use [runtime.Goexit] or panic inside it.
func (p *rodPage) WithPanic(fail func(any)) *rodPage {
	n := *p
	n.e = genE(fail)

	return &n
}

// MustInfo is similar to [Page.Info].
func (p *rodPage) MustInfo() *proto2.TargetTargetInfo {
	info, err := p.Info()
	p.e(err)

	return info
}

// MustHTML is similar to [Page.HTML].
func (p *rodPage) MustHTML() string {
	html, err := p.HTML()
	p.e(err)

	return html
}

// MustCookies is similar to [Page.Cookies].
func (p *rodPage) MustCookies(urls ...string) []*proto2.NetworkCookie {
	cookies, err := p.Cookies(urls)
	p.e(err)

	return cookies
}

// MustSetCookies is similar to [Page.SetCookies].
// If the len(cookies) is 0 it will clear all the cookies.
func (p *rodPage) MustSetCookies(cookies ...*proto2.NetworkCookieParam) *rodPage {
	if len(cookies) == 0 {
		cookies = nil
	}

	p.e(p.SetCookies(cookies))

	return p
}

// MustSetExtraHeaders is similar to [Page.SetExtraHeaders].
func (p *rodPage) MustSetExtraHeaders(dict ...string) (cleanup func()) {
	cleanup, err := p.SetExtraHeaders(dict)
	p.e(err)

	return
}

// MustSetUserAgent is similar to [Page.SetUserAgent].
func (p *rodPage) MustSetUserAgent(req *proto2.NetworkSetUserAgentOverride) *rodPage {
	p.e(p.SetUserAgent(req))
	return p
}

// MustSetBlockedURLs is similar to [Page.SetBlockedURLs].
func (p *rodPage) MustSetBlockedURLs(urls ...string) *rodPage {
	p.e(p.SetBlockedURLs(urls))
	return p
}

// MustNavigate is similar to [Page.Navigate].
func (p *rodPage) MustNavigate(url string) *rodPage {
	p.e(p.Navigate(url))
	return p
}

// MustResetNavigationHistory is similar to [Page.ResetNavigationHistory].
func (p *rodPage) MustResetNavigationHistory() *rodPage {
	p.e(p.ResetNavigationHistory())
	return p
}

// MustReload is similar to [Page.Reload].
func (p *rodPage) MustReload() *rodPage {
	p.e(p.Reload())
	return p
}

// MustActivate is similar to [Page.Activate].
func (p *rodPage) MustActivate() *rodPage {
	p.e(p.Activate())
	return p
}

// MustNavigateBack is similar to [Page.NavigateBack].
func (p *rodPage) MustNavigateBack() *rodPage {
	p.e(p.NavigateBack())
	return p
}

// MustNavigateForward is similar to [Page.NavigateForward].
func (p *rodPage) MustNavigateForward() *rodPage {
	p.e(p.NavigateForward())
	return p
}

// MustGetWindow is similar to [Page.GetWindow].
func (p *rodPage) MustGetWindow() *proto2.BrowserBounds {
	bounds, err := p.GetWindow()
	p.e(err)

	return bounds
}

// MustSetWindow is similar to [Page.SetWindow].
func (p *rodPage) MustSetWindow(left, top, width, height int) *rodPage {
	p.e(p.SetWindow(&proto2.BrowserBounds{
		Left:        gson.Int(left),
		Top:         gson.Int(top),
		Width:       gson.Int(width),
		Height:      gson.Int(height),
		WindowState: proto2.BrowserWindowStateNormal,
	}))

	return p
}

// MustWindowMinimize is similar to [Page.WindowMinimize].
func (p *rodPage) MustWindowMinimize() *rodPage {
	p.e(p.SetWindow(&proto2.BrowserBounds{
		WindowState: proto2.BrowserWindowStateMinimized,
	}))

	return p
}

// MustWindowMaximize is similar to [Page.WindowMaximize].
func (p *rodPage) MustWindowMaximize() *rodPage {
	p.e(p.SetWindow(&proto2.BrowserBounds{
		WindowState: proto2.BrowserWindowStateMaximized,
	}))

	return p
}

// MustWindowFullscreen is similar to [Page.WindowFullscreen].
func (p *rodPage) MustWindowFullscreen() *rodPage {
	p.e(p.SetWindow(&proto2.BrowserBounds{
		WindowState: proto2.BrowserWindowStateFullscreen,
	}))

	return p
}

// MustWindowNormal is similar to [Page.WindowNormal].
func (p *rodPage) MustWindowNormal() *rodPage {
	p.e(p.SetWindow(&proto2.BrowserBounds{
		WindowState: proto2.BrowserWindowStateNormal,
	}))

	return p
}

// MustSetViewport is similar to [Page.SetViewport].
func (p *rodPage) MustSetViewport(width, height int, deviceScaleFactor float64, mobile bool) *rodPage {
	p.e(p.SetViewport(&proto2.EmulationSetDeviceMetricsOverride{
		Width:             width,
		Height:            height,
		DeviceScaleFactor: deviceScaleFactor,
		Mobile:            mobile,
	}))

	return p
}

// MustEmulate is similar to [Page.Emulate].
func (p *rodPage) MustEmulate(device devices.Device) *rodPage {
	p.e(p.Emulate(device))
	return p
}

// MustStopLoading is similar to [Page.StopLoading].
func (p *rodPage) MustStopLoading() *rodPage {
	p.e(p.StopLoading())
	return p
}

// MustClose is similar to [Page.Close].
func (p *rodPage) MustClose() {
	p.e(p.Close())
}

// MustHandleDialog is similar to [Page.HandleDialog].
func (p *rodPage) MustHandleDialog() (wait func() *proto2.PageJavascriptDialogOpening, handle func(bool, string)) {
	w, h := p.HandleDialog()

	return w, func(accept bool, promptText string) {
		p.e(h(&proto2.PageHandleJavaScriptDialog{
			Accept:     accept,
			PromptText: promptText,
		}))
	}
}

// MustHandleFileDialog is similar to [Page.HandleFileDialog].
func (p *rodPage) MustHandleFileDialog() func(...string) {
	setFiles, err := p.HandleFileDialog()
	p.e(err)

	return func(paths ...string) {
		p.e(setFiles(paths))
	}
}

// MustScreenshot is similar to [Page.Screenshot].
// If the toFile is "", it Page.will save output to "tmp/screenshots" folder, time as the file name.
func (p *rodPage) MustScreenshot(toFile ...string) []byte {
	bin, err := p.Screenshot(false, nil)
	p.e(err)
	p.e(saveFile(saveFileTypeScreenshot, bin, toFile))

	return bin
}

// MustCaptureDOMSnapshot is similar to [Page.CaptureDOMSnapshot].
func (p *rodPage) MustCaptureDOMSnapshot() (domSnapshot *proto2.DOMSnapshotCaptureSnapshotResult) {
	domSnapshot, err := p.CaptureDOMSnapshot()
	p.e(err)

	return domSnapshot
}

// MustTriggerFavicon is similar to [PageTriggerFavicon].
func (p *rodPage) MustTriggerFavicon() *rodPage {
	p.e(p.TriggerFavicon())
	return p
}

// MustScreenshotFullPage is similar to [Page.ScreenshotFullPage].
// If the toFile is "", it Page.will save output to "tmp/screenshots" folder, time as the file name.
func (p *rodPage) MustScreenshotFullPage(toFile ...string) []byte {
	bin, err := p.Screenshot(true, nil)
	p.e(err)
	p.e(saveFile(saveFileTypeScreenshot, bin, toFile))

	return bin
}

// MustScrollScreenshot is similar to [Page.ScrollScreenshot].
// If the toFile is "", it Page.will save output to "tmp/screenshots" folder, time as the file name.
func (p *rodPage) MustScrollScreenshot(toFile ...string) []byte {
	bin, err := p.ScrollScreenshot(nil)
	p.e(err)
	p.e(saveFile(saveFileTypeScreenshot, bin, toFile))

	return bin
}

// MustPDF is similar to [Page.PDF].
// If the toFile is "", it Page.will save output to "tmp/pdf" folder, time as the file name.
func (p *rodPage) MustPDF(toFile ...string) []byte {
	r, err := p.PDF(&proto2.PagePrintToPDF{})
	p.e(err)
	bin, err := io.ReadAll(r)
	p.e(err)

	p.e(saveFile(saveFileTypePDF, bin, toFile))

	return bin
}

// MustWaitOpen is similar to [Page.WaitOpen].
func (p *rodPage) MustWaitOpen() (wait func() (newPage *rodPage)) {
	w := p.WaitOpen()

	return func() *rodPage {
		page, err := w()
		p.e(err)

		return page
	}
}

// MustWaitNavigation is similar to [Page.WaitNavigation].
func (p *rodPage) MustWaitNavigation() func() {
	return p.WaitNavigation(proto2.PageLifecycleEventNameNetworkAlmostIdle)
}

// MustWaitRequestIdle is similar to [Page.WaitRequestIdle].
func (p *rodPage) MustWaitRequestIdle(excludes ...string) (wait func()) {
	return p.WaitRequestIdle(300*time.Millisecond, nil, excludes, nil)
}

// MustWaitIdle is similar to [Page.WaitIdle].
func (p *rodPage) MustWaitIdle() *rodPage {
	p.e(p.WaitIdle(time.Minute))
	return p
}

// MustWaitDOMStable is similar to [Page.WaitDOMStable].
func (p *rodPage) MustWaitDOMStable() *rodPage {
	p.e(p.WaitDOMStable(time.Second, 0))
	return p
}

// MustWaitStable is similar to [Page.WaitStable].
func (p *rodPage) MustWaitStable() *rodPage {
	p.e(p.WaitStable(time.Second))
	return p
}

// MustWaitLoad is similar to [Page.WaitLoad].
func (p *rodPage) MustWaitLoad() *rodPage {
	p.e(p.WaitLoad())
	return p
}

// MustAddScriptTag is similar to [Page.AddScriptTag].
func (p *rodPage) MustAddScriptTag(url string) *rodPage {
	p.e(p.AddScriptTag(url, ""))
	return p
}

// MustAddStyleTag is similar to [Page.AddStyleTag].
func (p *rodPage) MustAddStyleTag(url string) *rodPage {
	p.e(p.AddStyleTag(url, ""))
	return p
}

// MustEvalOnNewDocument is similar to [Page.EvalOnNewDocument].
func (p *rodPage) MustEvalOnNewDocument(js string) {
	_, err := p.EvalOnNewDocument(js)
	p.e(err)
}

// MustExpose is similar to [Page.Expose].
func (p *rodPage) MustExpose(name string, fn func(gson.JSON) (any, error)) (stop func()) {
	s, err := p.Expose(name, fn)
	p.e(err)

	return func() { p.e(s()) }
}

// MustEval is similar to [Page.Eval].
func (p *rodPage) MustEval(js string, params ...any) gson.JSON {
	res, err := p.Eval(js, params...)
	p.e(err)

	return res.Value
}

// MustEvaluate is similar to [Page.Evaluate].
func (p *rodPage) MustEvaluate(opts *EvalOptions) *proto2.RuntimeRemoteObject {
	res, err := p.Evaluate(opts)
	p.e(err)

	return res
}

// MustWait is similar to [Page.Wait].
func (p *rodPage) MustWait(js string, params ...any) *rodPage {
	p.e(p.Wait(Eval(js, params...)))
	return p
}

// MustWaitElementsMoreThan is similar to [Page.WaitElementsMoreThan].
func (p *rodPage) MustWaitElementsMoreThan(selector string, num int) *rodPage {
	p.e(p.WaitElementsMoreThan(selector, num))
	return p
}

// MustObjectToJSON is similar to [Page.ObjectToJSON].
func (p *rodPage) MustObjectToJSON(obj *proto2.RuntimeRemoteObject) gson.JSON {
	j, err := p.ObjectToJSON(obj)
	p.e(err)

	return j
}

// MustObjectsToJSON is similar to [Page.ObjectsToJSON].
func (p *rodPage) MustObjectsToJSON(list []*proto2.RuntimeRemoteObject) gson.JSON {
	arr := make([]any, 0, len(list))

	for _, obj := range list {
		j, err := p.ObjectToJSON(obj)
		p.e(err)

		arr = append(arr, j.Val())
	}

	return gson.New(arr)
}

// MustElementFromNode is similar to [Page.ElementFromNode].
func (p *rodPage) MustElementFromNode(node *proto2.DOMNode) *rodElement {
	el, err := p.ElementFromNode(node)
	p.e(err)

	return el
}

// MustElementFromPoint is similar to [Page.ElementFromPoint].
func (p *rodPage) MustElementFromPoint(left, top int) *rodElement {
	el, err := p.ElementFromPoint(left, top)
	p.e(err)

	return el
}

// MustRelease is similar to [Page.Release].
func (p *rodPage) MustRelease(obj *proto2.RuntimeRemoteObject) *rodPage {
	p.e(p.Release(obj))
	return p
}

// MustHas is similar to [Page.Has].
func (p *rodPage) MustHas(selector string) bool {
	has, _, err := p.Has(selector)
	p.e(err)

	return has
}

// MustHasX is similar to [Page.HasX].
func (p *rodPage) MustHasX(selector string) bool {
	has, _, err := p.HasX(selector)
	p.e(err)

	return has
}

// MustHasR is similar to [Page.HasR].
func (p *rodPage) MustHasR(selector, regex string) bool {
	has, _, err := p.HasR(selector, regex)
	p.e(err)

	return has
}

// MustSearch is similar to [Page.Search].
// It only returns the first element in the search result.
func (p *rodPage) MustSearch(query string) *rodElement {
	res, err := p.Search(query)
	p.e(err)
	res.Release()

	return res.First
}

// MustElement is similar to [Page.Element].
func (p *rodPage) MustElement(selector string) *rodElement {
	el, err := p.Element(selector)
	p.e(err)

	return el
}

// MustElementR is similar to [Page.ElementR].
func (p *rodPage) MustElementR(selector, jsRegex string) *rodElement {
	el, err := p.ElementR(selector, jsRegex)
	p.e(err)

	return el
}

// MustElementX is similar to [Page.ElementX].
func (p *rodPage) MustElementX(xPath string) *rodElement {
	el, err := p.ElementX(xPath)
	p.e(err)

	return el
}

// MustElementByJS is similar to [Page.ElementByJS].
func (p *rodPage) MustElementByJS(js string, params ...any) *rodElement {
	el, err := p.ElementByJS(Eval(js, params...))
	p.e(err)

	return el
}

// MustElements is similar to [Page.Elements].
func (p *rodPage) MustElements(selector string) Elements {
	list, err := p.Elements(selector)
	p.e(err)

	return list
}

// MustElementsX is similar to [Page.ElementsX].
func (p *rodPage) MustElementsX(xpath string) Elements {
	list, err := p.ElementsX(xpath)
	p.e(err)

	return list
}

// MustElementsByJS is similar to [Page.ElementsByJS].
func (p *rodPage) MustElementsByJS(js string, params ...any) Elements {
	list, err := p.ElementsByJS(Eval(js, params...))
	p.e(err)

	return list
}

// MustElementByJS is similar to [RaceContext.ElementByJS].
func (rc *RaceContext) MustElementByJS(js string, params []any) *RaceContext {
	return rc.ElementByJS(Eval(js, params...))
}

// MustHandle is similar to [RaceContext.Handle].
func (rc *RaceContext) MustHandle(callback func(*rodElement)) *RaceContext {
	return rc.Handle(func(e *rodElement) error {
		callback(e)
		return nil
	})
}

// MustDo is similar to [RaceContext.Do].
func (rc *RaceContext) MustDo() *rodElement {
	el, err := rc.Do()
	rc.page.e(err)

	return el
}

// MustMoveTo is similar to [Mouse.Move].
func (m *Mouse) MustMoveTo(x, y float64) *Mouse {
	m.page.e(m.MoveTo(proto2.NewPoint(x, y)))
	return m
}

// MustScroll is similar to [Mouse.Scroll].
func (m *Mouse) MustScroll(x, y float64) *Mouse {
	m.page.e(m.Scroll(x, y, 0))
	return m
}

// MustDown is similar to [Mouse.Down].
func (m *Mouse) MustDown(button proto2.InputMouseButton) *Mouse {
	m.page.e(m.Down(button, 1))
	return m
}

// MustUp is similar to [Mouse.Up].
func (m *Mouse) MustUp(button proto2.InputMouseButton) *Mouse {
	m.page.e(m.Up(button, 1))
	return m
}

// MustClick is similar to [Mouse.Click].
func (m *Mouse) MustClick(button proto2.InputMouseButton) *Mouse {
	m.page.e(m.Click(button, 1))
	return m
}

// MustType is similar to [Keyboard.Type].
func (k *Keyboard) MustType(key ...input.Key) *Keyboard {
	k.page.e(k.Type(key...))
	return k
}

// MustDo is similar to [KeyActions.Do].
func (ka *KeyActions) MustDo() {
	ka.keyboard.page.e(ka.Do())
}

// MustInsertText is similar to [Page.InsertText].
func (p *rodPage) MustInsertText(text string) *rodPage {
	p.e(p.InsertText(text))
	return p
}

// MustStart is similar to [Touch.Start].
func (t *Touch) MustStart(points ...*proto2.InputTouchPoint) *Touch {
	t.page.e(t.Start(points...))
	return t
}

// MustMove is similar to [Touch.Move].
func (t *Touch) MustMove(points ...*proto2.InputTouchPoint) *Touch {
	t.page.e(t.Move(points...))
	return t
}

// MustEnd is similar to [Touch.End].
func (t *Touch) MustEnd() *Touch {
	t.page.e(t.End())
	return t
}

// MustCancel is similar to [Touch.Cancel].
func (t *Touch) MustCancel() *Touch {
	t.page.e(t.Cancel())
	return t
}

// MustTap is similar to [Touch.Tap].
func (t *Touch) MustTap(x, y float64) *Touch {
	t.page.e(t.Tap(x, y))
	return t
}

// WithPanic returns an element clone with the specified panic function.
// The fail must stop the current goroutine's execution immediately, such as use [runtime.Goexit] or panic inside it.
func (el *rodElement) WithPanic(fail func(any)) *rodElement {
	n := *el
	n.e = genE(fail)

	return &n
}

// MustDescribe is similar to [Element.Describe].
func (el *rodElement) MustDescribe() *proto2.DOMNode {
	node, err := el.Describe(1, false)
	el.e(err)

	return node
}

// MustShadowRoot is similar to [Element.ShadowRoot].
func (el *rodElement) MustShadowRoot() *rodElement {
	node, err := el.ShadowRoot()
	el.e(err)

	return node
}

// MustFrame is similar to [Element.Frame].
func (el *rodElement) MustFrame() *rodPage {
	p, err := el.Frame()
	el.e(err)

	return p
}

// MustFocus is similar to [Element.Focus].
func (el *rodElement) MustFocus() *rodElement {
	el.e(el.Focus())
	return el
}

// MustScrollIntoView is similar to [Element.ScrollIntoView].
func (el *rodElement) MustScrollIntoView() *rodElement {
	el.e(el.ScrollIntoView())
	return el
}

// MustHover is similar to [Element.Hover].
func (el *rodElement) MustHover() *rodElement {
	el.e(el.Hover())
	return el
}

// MustClick is similar to [Element.Click].
func (el *rodElement) MustClick() *rodElement {
	el.e(el.Click(proto2.InputMouseButtonLeft, 1))
	return el
}

// MustDoubleClick is similar to [Element.Click].
func (el *rodElement) MustDoubleClick() *rodElement {
	el.e(el.Click(proto2.InputMouseButtonLeft, 2))
	return el
}

// MustTap is similar to [Element.Tap].
func (el *rodElement) MustTap() *rodElement {
	el.e(el.Tap())
	return el
}

// MustInteractable is similar to [Element.Interactable].
func (el *rodElement) MustInteractable() bool {
	_, err := el.Interactable()
	if errors.Is(err, &NotInteractableError{}) {
		return false
	}

	el.e(err)

	return true
}

// MustWaitInteractable is similar to [Element.WaitInteractable].
func (el *rodElement) MustWaitInteractable() *rodElement {
	el.e(el.WaitInteractable())
	return el
}

// MustType is similar to [Element.Type].
func (el *rodElement) MustType(keys ...input.Key) *rodElement {
	el.e(el.Type(keys...))
	return el
}

// MustKeyActions is similar to [Element.KeyActions].
func (el *rodElement) MustKeyActions() *KeyActions {
	ka, err := el.KeyActions()
	el.e(err)

	return ka
}

// MustSelectText is similar to [Element.SelectText].
func (el *rodElement) MustSelectText(regex string) *rodElement {
	el.e(el.SelectText(regex))
	return el
}

// MustSelectAllText is similar to [Element.SelectAllText].
func (el *rodElement) MustSelectAllText() *rodElement {
	el.e(el.SelectAllText())
	return el
}

// MustInput is similar to [Element.Input].
func (el *rodElement) MustInput(text string) *rodElement {
	el.e(el.Input(text))
	return el
}

// MustInputTime is similar to [Element.Input].
func (el *rodElement) MustInputTime(t time.Time) *rodElement {
	el.e(el.InputTime(t))
	return el
}

// MustInputColor is similar to [Element.InputColor].
func (el *rodElement) MustInputColor(color string) *rodElement {
	el.e(el.InputColor(color))
	return el
}

// MustBlur is similar to [Element.Blur].
func (el *rodElement) MustBlur() *rodElement {
	el.e(el.Blur())
	return el
}

// MustSelect is similar to [Element.Select].
func (el *rodElement) MustSelect(selectors ...string) *rodElement {
	el.e(el.Select(selectors, true, SelectorTypeText))
	return el
}

// MustMatches is similar to [Element.Matches].
func (el *rodElement) MustMatches(selector string) bool {
	res, err := el.Matches(selector)
	el.e(err)

	return res
}

// MustAttribute is similar to [Element.Attribute].
func (el *rodElement) MustAttribute(name string) *string {
	attr, err := el.Attribute(name)
	el.e(err)

	return attr
}

// MustProperty is similar to [Element.Property].
func (el *rodElement) MustProperty(name string) gson.JSON {
	prop, err := el.Property(name)
	el.e(err)

	return prop
}

// MustDisabled is similar to [Element.Disabled].
func (el *rodElement) MustDisabled() bool {
	disabled, err := el.Disabled()
	el.e(err)

	return disabled
}

// MustContainsElement is similar to [Element.ContainsElement].
func (el *rodElement) MustContainsElement(target *rodElement) bool {
	contains, err := el.ContainsElement(target)
	el.e(err)

	return contains
}

// MustSetFiles is similar to [Element.SetFiles].
func (el *rodElement) MustSetFiles(paths ...string) *rodElement {
	el.e(el.SetFiles(paths))
	return el
}

// MustSetDocumentContent is similar to [Page.SetDocumentContent].
func (p *rodPage) MustSetDocumentContent(html string) *rodPage {
	p.e(p.SetDocumentContent(html))
	return p
}

// MustText is similar to [Element.Text].
func (el *rodElement) MustText() string {
	s, err := el.Text()
	el.e(err)

	return s
}

// MustHTML is similar to [Element.HTML].
func (el *rodElement) MustHTML() string {
	s, err := el.HTML()
	el.e(err)

	return s
}

// MustVisible is similar to [Element.Visible].
func (el *rodElement) MustVisible() bool {
	v, err := el.Visible()
	el.e(err)

	return v
}

// MustWaitLoad is similar to [Element.WaitLoad].
func (el *rodElement) MustWaitLoad() *rodElement {
	el.e(el.WaitLoad())
	return el
}

// MustWaitStable is similar to [Element.WaitStable].
func (el *rodElement) MustWaitStable() *rodElement {
	el.e(el.WaitStable(300 * time.Millisecond))
	return el
}

// MustWait is similar to [Element.Wait].
func (el *rodElement) MustWait(js string, params ...any) *rodElement {
	el.e(el.Wait(Eval(js, params...)))
	return el
}

// MustWaitVisible is similar to [Element.WaitVisible].
func (el *rodElement) MustWaitVisible() *rodElement {
	el.e(el.WaitVisible())
	return el
}

// MustWaitInvisible is similar to [Element.WaitInvisible]..
func (el *rodElement) MustWaitInvisible() *rodElement {
	el.e(el.WaitInvisible())
	return el
}

// MustWaitEnabled is similar to [Element.WaitEnabled].
func (el *rodElement) MustWaitEnabled() *rodElement {
	el.e(el.WaitEnabled())
	return el
}

// MustWaitWritable is similar to [Element.WaitWritable].
func (el *rodElement) MustWaitWritable() *rodElement {
	el.e(el.WaitWritable())
	return el
}

// MustShape is similar to [Element.Shape].
func (el *rodElement) MustShape() *proto2.DOMGetContentQuadsResult {
	shape, err := el.Shape()
	el.e(err)

	return shape
}

// MustCanvasToImage is similar to [Element.CanvasToImage].
func (el *rodElement) MustCanvasToImage() []byte {
	bin, err := el.CanvasToImage("", -1)
	el.e(err)

	return bin
}

// MustResource is similar to [Element.Resource].
func (el *rodElement) MustResource() []byte {
	bin, err := el.Resource()
	el.e(err)

	return bin
}

// MustBackgroundImage is similar to [Element.BackgroundImage].
func (el *rodElement) MustBackgroundImage() []byte {
	bin, err := el.BackgroundImage()
	el.e(err)

	return bin
}

// MustScreenshot is similar to [Element.Screenshot].
func (el *rodElement) MustScreenshot(toFile ...string) []byte {
	bin, err := el.Screenshot(proto2.PageCaptureScreenshotFormatPng, 0)
	el.e(err)
	el.e(saveFile(saveFileTypeScreenshot, bin, toFile))

	return bin
}

// MustRelease is similar to [Element.Release].
func (el *rodElement) MustRelease() {
	el.e(el.Release())
}

// MustRemove is similar to [Element.Remove].
func (el *rodElement) MustRemove() {
	el.e(el.Remove())
}

// MustEval is similar to [Element.Eval].
func (el *rodElement) MustEval(js string, params ...any) gson.JSON {
	res, err := el.Eval(js, params...)
	el.e(err)

	return res.Value
}

// MustHas is similar to [Element.Has].
func (el *rodElement) MustHas(selector string) bool {
	has, _, err := el.Has(selector)
	el.e(err)

	return has
}

// MustHasX is similar to [Element.HasX].
func (el *rodElement) MustHasX(selector string) bool {
	has, _, err := el.HasX(selector)
	el.e(err)

	return has
}

// MustHasR is similar to [Element.HasR].
func (el *rodElement) MustHasR(selector, regex string) bool {
	has, _, err := el.HasR(selector, regex)
	el.e(err)

	return has
}

// MustElement is similar to [Element.Element].
func (el *rodElement) MustElement(selector string) *rodElement {
	el, err := el.Element(selector)
	el.e(err)

	return el
}

// MustElementX is similar to [Element.ElementX].
func (el *rodElement) MustElementX(xpath string) *rodElement {
	el, err := el.ElementX(xpath)
	el.e(err)

	return el
}

// MustElementByJS is similar to [Element.ElementByJS].
func (el *rodElement) MustElementByJS(js string, params ...any) *rodElement {
	el, err := el.ElementByJS(Eval(js, params...))
	el.e(err)

	return el
}

// MustParent is similar to [Element.Parent].
func (el *rodElement) MustParent() *rodElement {
	parent, err := el.Parent()
	el.e(err)

	return parent
}

// MustParents is similar to [Element.Parents].
func (el *rodElement) MustParents(selector string) Elements {
	list, err := el.Parents(selector)
	el.e(err)

	return list
}

// MustNext is similar to [Element.Next].
func (el *rodElement) MustNext() *rodElement {
	parent, err := el.Next()
	el.e(err)

	return parent
}

// MustPrevious is similar to [Element.Previous].
func (el *rodElement) MustPrevious() *rodElement {
	parent, err := el.Previous()
	el.e(err)

	return parent
}

// MustElementR is similar to [Element.ElementR].
func (el *rodElement) MustElementR(selector, regex string) *rodElement {
	sub, err := el.ElementR(selector, regex)
	el.e(err)

	return sub
}

// MustElements is similar to [Element.Elements].
func (el *rodElement) MustElements(selector string) Elements {
	list, err := el.Elements(selector)
	el.e(err)

	return list
}

// MustElementsX is similar to [Element.ElementsX].
func (el *rodElement) MustElementsX(xpath string) Elements {
	list, err := el.ElementsX(xpath)
	el.e(err)

	return list
}

// MustElementsByJS is similar to [Element.ElementsByJS].
func (el *rodElement) MustElementsByJS(js string, params ...any) Elements {
	list, err := el.ElementsByJS(Eval(js, params...))
	el.e(err)

	return list
}

// MustAdd is similar to [HijackRouter.Add].
func (r *rodHijackRouter) MustAdd(pattern string, handler func(*Hijack)) *rodHijackRouter {
	r.browser.e(r.Add(pattern, "", handler))
	return r
}

// MustRemove is similar to [HijackRouter.Remove].
func (r *rodHijackRouter) MustRemove(pattern string) *rodHijackRouter {
	r.browser.e(r.Remove(pattern))
	return r
}

// MustStop is similar to [HijackRouter.Stop].
func (r *rodHijackRouter) MustStop() {
	r.browser.e(r.Stop())
}

// MustLoadResponse is similar to [Hijack.LoadResponse].
func (h *Hijack) MustLoadResponse() {
	h.browser.e(h.LoadResponse(http.DefaultClient, true))
}

// MustEqual is similar to [Element.Equal].
func (el *rodElement) MustEqual(elm *rodElement) bool {
	res, err := el.Equal(elm)
	el.e(err)

	return res
}

// MustMoveMouseOut is similar to [Element.MoveMouseOut].
func (el *rodElement) MustMoveMouseOut() *rodElement {
	el.e(el.MoveMouseOut())
	return el
}

// MustGetXPath is similar to [Element.GetXPath].
func (el *rodElement) MustGetXPath(optimized bool) string {
	xpath, err := el.GetXPath(optimized)
	el.e(err)

	return xpath
}

// MustGet an elem from the pool. Use the [Pool[T].Put] to make it reusable later.
func (p Pool[T]) MustGet(create func() *T) *T {
	elem := <-p
	if elem == nil {
		elem = create()
	}

	return elem
}
