// This file contains the methods that panics when error return value is not nil.
// Their function names are all prefixed with Must.
// A function here is usually a wrapper for the error version with fixed default options to make it easier to use.
//
// For example the source code of [Element.Click] and [Element.MustClick]. MustClick has no argument.
// But `Click` has a `button` argument to decide which button to click.
// `MustClick` feels like a version of `Click` with some default arguments.

package engine

import (
	"strings"

	proto2 "github.com/inovacc/scout/internal/engine/lib/proto"
	"github.com/ysmood/gson"
)

// It must be generated by genE.
type eFunc func(args ...any)

// Generate a eFunc with the specified fail function.
// If the last arg of eFunc is error the fail will be called.
func genE(fail func(any)) eFunc {
	return func(args ...any) {
		err, ok := args[len(args)-1].(error)
		if ok {
			fail(err)
		}
	}
}

// WithPanic returns a browser clone with the specified panic function.
// The fail must stop the current goroutine's execution immediately, such as use [runtime.Goexit] or panic inside it.
func (b *rodBrowser) WithPanic(fail func(any)) *rodBrowser {
	n := *b
	n.e = genE(fail)

	return &n
}

// MustPage is similar to [Browser.Page].
// The url list will be joined by "/".
func (b *rodBrowser) MustPage(url ...string) *rodPage {
	p, err := b.Page(proto2.TargetCreateTarget{URL: strings.Join(url, "/")})
	b.e(err)

	return p
}

// MustPageFromTargetID is similar to [Browser.PageFromTargetID].
func (b *rodBrowser) MustPageFromTargetID(targetID proto2.TargetTargetID) *rodPage {
	p, err := b.PageFromTarget(targetID)
	b.e(err)

	return p
}

// WithPanic returns a page clone with the specified panic function.
// The fail must stop the current goroutine's execution immediately, such as use [runtime.Goexit] or panic inside it.
func (p *rodPage) WithPanic(fail func(any)) *rodPage {
	n := *p
	n.e = genE(fail)

	return &n
}

// MustInfo is similar to [Page.Info].
func (p *rodPage) MustInfo() *proto2.TargetTargetInfo {
	info, err := p.Info()
	p.e(err)

	return info
}

// MustHandleDialog is similar to [Page.HandleDialog].
func (p *rodPage) MustHandleDialog() (wait func() *proto2.PageJavascriptDialogOpening, handle func(bool, string)) {
	w, h := p.HandleDialog()

	return w, func(accept bool, promptText string) {
		p.e(h(&proto2.PageHandleJavaScriptDialog{
			Accept:     accept,
			PromptText: promptText,
		}))
	}
}

// MustScreenshot is similar to [Page.Screenshot].
// If the toFile is "", it Page.will save output to "tmp/screenshots" folder, time as the file name.
func (p *rodPage) MustScreenshot(toFile ...string) []byte {
	bin, err := p.Screenshot(false, nil)
	p.e(err)
	p.e(saveFile(saveFileTypeScreenshot, bin, toFile))

	return bin
}

// MustEval is similar to [Page.Eval].
func (p *rodPage) MustEval(js string, params ...any) gson.JSON {
	res, err := p.Eval(js, params...)
	p.e(err)

	return res.Value
}

// MustEvaluate is similar to [Page.Evaluate].
func (p *rodPage) MustEvaluate(opts *EvalOptions) *proto2.RuntimeRemoteObject {
	res, err := p.Evaluate(opts)
	p.e(err)

	return res
}

// MustElement is similar to [Page.Element].
func (p *rodPage) MustElement(selector string) *rodElement {
	el, err := p.Element(selector)
	p.e(err)

	return el
}

// MustHandle is similar to [RaceContext.Handle].
func (rc *RaceContext) MustHandle(callback func(*rodElement)) *RaceContext {
	return rc.Handle(func(e *rodElement) error {
		callback(e)
		return nil
	})
}

// WithPanic returns an element clone with the specified panic function.
// The fail must stop the current goroutine's execution immediately, such as use [runtime.Goexit] or panic inside it.
func (el *rodElement) WithPanic(fail func(any)) *rodElement {
	n := *el
	n.e = genE(fail)

	return &n
}

// MustClick is similar to [Element.Click].
func (el *rodElement) MustClick() *rodElement {
	el.e(el.Click(proto2.InputMouseButtonLeft, 1))
	return el
}

// MustInput is similar to [Element.Input].
func (el *rodElement) MustInput(text string) *rodElement {
	el.e(el.Input(text))
	return el
}

// MustEval is similar to [Element.Eval].
func (el *rodElement) MustEval(js string, params ...any) gson.JSON {
	res, err := el.Eval(js, params...)
	el.e(err)

	return res.Value
}

// MustElement is similar to [Element.Element].
func (el *rodElement) MustElement(selector string) *rodElement {
	el, err := el.Element(selector)
	el.e(err)

	return el
}

// MustScreenshot is similar to [Element.Screenshot].
func (el *rodElement) MustScreenshot(toFile ...string) []byte {
	bin, err := el.Screenshot(proto2.PageCaptureScreenshotFormatPng, 0)
	el.e(err)
	el.e(saveFile(saveFileTypeScreenshot, bin, toFile))

	return bin
}

// MustStart is similar to [Touch.Start].
func (t *Touch) MustStart(points ...*proto2.InputTouchPoint) *Touch {
	t.page.e(t.Start(points...))
	return t
}
