// generated by "lib/launcher/revision"

package launcher

// RevisionDefault for chromium. Compile-time fallback; runtime value comes from browser.json.
const RevisionDefault = 1588893

// RevisionPlaywright for arm linux. Compile-time fallback; runtime value comes from browser.json.
const RevisionPlaywright = 1124
