// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: grpc/proto/scout.proto

package scoutpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_grpc_proto_scout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{0}
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Headless      bool                   `protobuf:"varint,1,opt,name=headless,proto3" json:"headless,omitempty"`
	Stealth       bool                   `protobuf:"varint,2,opt,name=stealth,proto3" json:"stealth,omitempty"`
	Proxy         string                 `protobuf:"bytes,3,opt,name=proxy,proto3" json:"proxy,omitempty"`
	UserAgent     string                 `protobuf:"bytes,4,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	InitialUrl    string                 `protobuf:"bytes,7,opt,name=initial_url,json=initialUrl,proto3" json:"initial_url,omitempty"`
	Record        bool                   `protobuf:"varint,8,opt,name=record,proto3" json:"record,omitempty"`                              // start recording immediately
	CaptureBody   bool                   `protobuf:"varint,9,opt,name=capture_body,json=captureBody,proto3" json:"capture_body,omitempty"` // capture response bodies
	Maximized     bool                   `protobuf:"varint,10,opt,name=maximized,proto3" json:"maximized,omitempty"`                       // start window maximized
	Devtools      bool                   `protobuf:"varint,11,opt,name=devtools,proto3" json:"devtools,omitempty"`                         // open Chrome DevTools automatically
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetHeadless() bool {
	if x != nil {
		return x.Headless
	}
	return false
}

func (x *CreateSessionRequest) GetStealth() bool {
	if x != nil {
		return x.Stealth
	}
	return false
}

func (x *CreateSessionRequest) GetProxy() string {
	if x != nil {
		return x.Proxy
	}
	return ""
}

func (x *CreateSessionRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *CreateSessionRequest) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CreateSessionRequest) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CreateSessionRequest) GetInitialUrl() string {
	if x != nil {
		return x.InitialUrl
	}
	return ""
}

func (x *CreateSessionRequest) GetRecord() bool {
	if x != nil {
		return x.Record
	}
	return false
}

func (x *CreateSessionRequest) GetCaptureBody() bool {
	if x != nil {
		return x.CaptureBody
	}
	return false
}

func (x *CreateSessionRequest) GetMaximized() bool {
	if x != nil {
		return x.Maximized
	}
	return false
}

func (x *CreateSessionRequest) GetDevtools() bool {
	if x != nil {
		return x.Devtools
	}
	return false
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CreateSessionResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{3}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type NavigateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	WaitStable    bool                   `protobuf:"varint,3,opt,name=wait_stable,json=waitStable,proto3" json:"wait_stable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateRequest) Reset() {
	*x = NavigateRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateRequest) ProtoMessage() {}

func (x *NavigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateRequest.ProtoReflect.Descriptor instead.
func (*NavigateRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{4}
}

func (x *NavigateRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *NavigateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NavigateRequest) GetWaitStable() bool {
	if x != nil {
		return x.WaitStable
	}
	return false
}

type NavigateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateResponse) Reset() {
	*x = NavigateResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateResponse) ProtoMessage() {}

func (x *NavigateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateResponse.ProtoReflect.Descriptor instead.
func (*NavigateResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{5}
}

func (x *NavigateResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NavigateResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NavigateResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ElementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"` // CSS selector or XPath
	Xpath         bool                   `protobuf:"varint,3,opt,name=xpath,proto3" json:"xpath,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementRequest) Reset() {
	*x = ElementRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementRequest) ProtoMessage() {}

func (x *ElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementRequest.ProtoReflect.Descriptor instead.
func (*ElementRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{6}
}

func (x *ElementRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ElementRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *ElementRequest) GetXpath() bool {
	if x != nil {
		return x.Xpath
	}
	return false
}

type TypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ClearFirst    bool                   `protobuf:"varint,4,opt,name=clear_first,json=clearFirst,proto3" json:"clear_first,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeRequest) Reset() {
	*x = TypeRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeRequest) ProtoMessage() {}

func (x *TypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeRequest.ProtoReflect.Descriptor instead.
func (*TypeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{7}
}

func (x *TypeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TypeRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *TypeRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TypeRequest) GetClearFirst() bool {
	if x != nil {
		return x.ClearFirst
	}
	return false
}

type SelectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectRequest) Reset() {
	*x = SelectRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectRequest) ProtoMessage() {}

func (x *SelectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectRequest.ProtoReflect.Descriptor instead.
func (*SelectRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{8}
}

func (x *SelectRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SelectRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *SelectRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`             // e.g. "Enter", "Tab", "Escape"
	Modifiers     []string               `protobuf:"bytes,3,rep,name=modifiers,proto3" json:"modifiers,omitempty"` // "ctrl", "shift", "alt"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyRequest) Reset() {
	*x = KeyRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyRequest) ProtoMessage() {}

func (x *KeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyRequest.ProtoReflect.Descriptor instead.
func (*KeyRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{9}
}

func (x *KeyRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyRequest) GetModifiers() []string {
	if x != nil {
		return x.Modifiers
	}
	return nil
}

type AttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Attribute     string                 `protobuf:"bytes,3,opt,name=attribute,proto3" json:"attribute,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeRequest) Reset() {
	*x = AttributeRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeRequest) ProtoMessage() {}

func (x *AttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeRequest.ProtoReflect.Descriptor instead.
func (*AttributeRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{10}
}

func (x *AttributeRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AttributeRequest) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *AttributeRequest) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

type TextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextResponse) Reset() {
	*x = TextResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextResponse) ProtoMessage() {}

func (x *TextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextResponse.ProtoReflect.Descriptor instead.
func (*TextResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{11}
}

func (x *TextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type BoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResponse) Reset() {
	*x = BoolResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResponse) ProtoMessage() {}

func (x *BoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResponse.ProtoReflect.Descriptor instead.
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{12}
}

func (x *BoolResponse) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

type EvalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalRequest) Reset() {
	*x = EvalRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalRequest) ProtoMessage() {}

func (x *EvalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalRequest.ProtoReflect.Descriptor instead.
func (*EvalRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{13}
}

func (x *EvalRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *EvalRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type EvalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // JSON-encoded result
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalResponse) Reset() {
	*x = EvalResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalResponse) ProtoMessage() {}

func (x *EvalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalResponse.ProtoReflect.Descriptor instead.
func (*EvalResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{14}
}

func (x *EvalResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FullPage      bool                   `protobuf:"varint,2,opt,name=full_page,json=fullPage,proto3" json:"full_page,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`    // "png" or "jpeg"
	Quality       int32                  `protobuf:"varint,4,opt,name=quality,proto3" json:"quality,omitempty"` // jpeg quality 0-100
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{15}
}

func (x *ScreenshotRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ScreenshotRequest) GetFullPage() bool {
	if x != nil {
		return x.FullPage
	}
	return false
}

func (x *ScreenshotRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ScreenshotRequest) GetQuality() int32 {
	if x != nil {
		return x.Quality
	}
	return 0
}

type ScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{16}
}

func (x *ScreenshotResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ScreenshotResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type PDFResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PDFResponse) Reset() {
	*x = PDFResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PDFResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PDFResponse) ProtoMessage() {}

func (x *PDFResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PDFResponse.ProtoReflect.Descriptor instead.
func (*PDFResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{17}
}

func (x *PDFResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CaptureBody   bool                   `protobuf:"varint,2,opt,name=capture_body,json=captureBody,proto3" json:"capture_body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordingRequest) Reset() {
	*x = RecordingRequest{}
	mi := &file_grpc_proto_scout_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordingRequest) ProtoMessage() {}

func (x *RecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordingRequest.ProtoReflect.Descriptor instead.
func (*RecordingRequest) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{18}
}

func (x *RecordingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RecordingRequest) GetCaptureBody() bool {
	if x != nil {
		return x.CaptureBody
	}
	return false
}

type HARResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // HAR JSON
	EntryCount    int32                  `protobuf:"varint,2,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HARResponse) Reset() {
	*x = HARResponse{}
	mi := &file_grpc_proto_scout_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HARResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HARResponse) ProtoMessage() {}

func (x *HARResponse) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HARResponse.ProtoReflect.Descriptor instead.
func (*HARResponse) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{19}
}

func (x *HARResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HARResponse) GetEntryCount() int32 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

type BrowserEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Timestamp int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // unix millis
	// Types that are valid to be assigned to Event:
	//
	//	*BrowserEvent_RequestSent
	//	*BrowserEvent_ResponseReceived
	//	*BrowserEvent_Console
	//	*BrowserEvent_PageEvent
	//	*BrowserEvent_Error
	Event         isBrowserEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowserEvent) Reset() {
	*x = BrowserEvent{}
	mi := &file_grpc_proto_scout_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowserEvent) ProtoMessage() {}

func (x *BrowserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowserEvent.ProtoReflect.Descriptor instead.
func (*BrowserEvent) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{20}
}

func (x *BrowserEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *BrowserEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BrowserEvent) GetEvent() isBrowserEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *BrowserEvent) GetRequestSent() *NetworkRequestEvent {
	if x != nil {
		if x, ok := x.Event.(*BrowserEvent_RequestSent); ok {
			return x.RequestSent
		}
	}
	return nil
}

func (x *BrowserEvent) GetResponseReceived() *NetworkResponseEvent {
	if x != nil {
		if x, ok := x.Event.(*BrowserEvent_ResponseReceived); ok {
			return x.ResponseReceived
		}
	}
	return nil
}

func (x *BrowserEvent) GetConsole() *ConsoleEvent {
	if x != nil {
		if x, ok := x.Event.(*BrowserEvent_Console); ok {
			return x.Console
		}
	}
	return nil
}

func (x *BrowserEvent) GetPageEvent() *PageEvent {
	if x != nil {
		if x, ok := x.Event.(*BrowserEvent_PageEvent); ok {
			return x.PageEvent
		}
	}
	return nil
}

func (x *BrowserEvent) GetError() *ErrorEvent {
	if x != nil {
		if x, ok := x.Event.(*BrowserEvent_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isBrowserEvent_Event interface {
	isBrowserEvent_Event()
}

type BrowserEvent_RequestSent struct {
	RequestSent *NetworkRequestEvent `protobuf:"bytes,10,opt,name=request_sent,json=requestSent,proto3,oneof"`
}

type BrowserEvent_ResponseReceived struct {
	ResponseReceived *NetworkResponseEvent `protobuf:"bytes,11,opt,name=response_received,json=responseReceived,proto3,oneof"`
}

type BrowserEvent_Console struct {
	Console *ConsoleEvent `protobuf:"bytes,12,opt,name=console,proto3,oneof"`
}

type BrowserEvent_PageEvent struct {
	PageEvent *PageEvent `protobuf:"bytes,13,opt,name=page_event,json=pageEvent,proto3,oneof"`
}

type BrowserEvent_Error struct {
	Error *ErrorEvent `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

func (*BrowserEvent_RequestSent) isBrowserEvent_Event() {}

func (*BrowserEvent_ResponseReceived) isBrowserEvent_Event() {}

func (*BrowserEvent_Console) isBrowserEvent_Event() {}

func (*BrowserEvent_PageEvent) isBrowserEvent_Event() {}

func (*BrowserEvent_Error) isBrowserEvent_Event() {}

type NetworkRequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PostData      string                 `protobuf:"bytes,5,opt,name=post_data,json=postData,proto3" json:"post_data,omitempty"`
	ResourceType  string                 `protobuf:"bytes,6,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkRequestEvent) Reset() {
	*x = NetworkRequestEvent{}
	mi := &file_grpc_proto_scout_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRequestEvent) ProtoMessage() {}

func (x *NetworkRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRequestEvent.ProtoReflect.Descriptor instead.
func (*NetworkRequestEvent) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{21}
}

func (x *NetworkRequestEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NetworkRequestEvent) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *NetworkRequestEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NetworkRequestEvent) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *NetworkRequestEvent) GetPostData() string {
	if x != nil {
		return x.PostData
	}
	return ""
}

func (x *NetworkRequestEvent) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type NetworkResponseEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	StatusText    string                 `protobuf:"bytes,4,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	MimeType      string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	RemoteIp      string                 `protobuf:"bytes,7,opt,name=remote_ip,json=remoteIp,proto3" json:"remote_ip,omitempty"`
	TimeMs        float64                `protobuf:"fixed64,8,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkResponseEvent) Reset() {
	*x = NetworkResponseEvent{}
	mi := &file_grpc_proto_scout_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkResponseEvent) ProtoMessage() {}

func (x *NetworkResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkResponseEvent.ProtoReflect.Descriptor instead.
func (*NetworkResponseEvent) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{22}
}

func (x *NetworkResponseEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *NetworkResponseEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NetworkResponseEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *NetworkResponseEvent) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *NetworkResponseEvent) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *NetworkResponseEvent) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *NetworkResponseEvent) GetRemoteIp() string {
	if x != nil {
		return x.RemoteIp
	}
	return ""
}

func (x *NetworkResponseEvent) GetTimeMs() float64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

type ConsoleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // "log", "warn", "error", "info"
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleEvent) Reset() {
	*x = ConsoleEvent{}
	mi := &file_grpc_proto_scout_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleEvent) ProtoMessage() {}

func (x *ConsoleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleEvent.ProtoReflect.Descriptor instead.
func (*ConsoleEvent) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{23}
}

func (x *ConsoleEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *ConsoleEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"` // "load", "domcontentloaded", "navigated", "dialog"
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Data          string                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageEvent) Reset() {
	*x = PageEvent{}
	mi := &file_grpc_proto_scout_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageEvent) ProtoMessage() {}

func (x *PageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageEvent.ProtoReflect.Descriptor instead.
func (*PageEvent) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{24}
}

func (x *PageEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PageEvent) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PageEvent) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_grpc_proto_scout_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{25}
}

func (x *ErrorEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RequestId string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // for correlating responses
	// Types that are valid to be assigned to Action:
	//
	//	*Command_Navigate
	//	*Command_Click
	//	*Command_Type
	//	*Command_PressKey
	//	*Command_Eval
	//	*Command_Screenshot
	//	*Command_Wait
	//	*Command_Scroll
	Action        isCommand_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_grpc_proto_scout_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{26}
}

func (x *Command) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Command) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Command) GetAction() isCommand_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *Command) GetNavigate() *NavigateAction {
	if x != nil {
		if x, ok := x.Action.(*Command_Navigate); ok {
			return x.Navigate
		}
	}
	return nil
}

func (x *Command) GetClick() *ClickAction {
	if x != nil {
		if x, ok := x.Action.(*Command_Click); ok {
			return x.Click
		}
	}
	return nil
}

func (x *Command) GetType() *TypeAction {
	if x != nil {
		if x, ok := x.Action.(*Command_Type); ok {
			return x.Type
		}
	}
	return nil
}

func (x *Command) GetPressKey() *KeyAction {
	if x != nil {
		if x, ok := x.Action.(*Command_PressKey); ok {
			return x.PressKey
		}
	}
	return nil
}

func (x *Command) GetEval() *EvalAction {
	if x != nil {
		if x, ok := x.Action.(*Command_Eval); ok {
			return x.Eval
		}
	}
	return nil
}

func (x *Command) GetScreenshot() *ScreenshotAction {
	if x != nil {
		if x, ok := x.Action.(*Command_Screenshot); ok {
			return x.Screenshot
		}
	}
	return nil
}

func (x *Command) GetWait() *WaitAction {
	if x != nil {
		if x, ok := x.Action.(*Command_Wait); ok {
			return x.Wait
		}
	}
	return nil
}

func (x *Command) GetScroll() *ScrollAction {
	if x != nil {
		if x, ok := x.Action.(*Command_Scroll); ok {
			return x.Scroll
		}
	}
	return nil
}

type isCommand_Action interface {
	isCommand_Action()
}

type Command_Navigate struct {
	Navigate *NavigateAction `protobuf:"bytes,10,opt,name=navigate,proto3,oneof"`
}

type Command_Click struct {
	Click *ClickAction `protobuf:"bytes,11,opt,name=click,proto3,oneof"`
}

type Command_Type struct {
	Type *TypeAction `protobuf:"bytes,12,opt,name=type,proto3,oneof"`
}

type Command_PressKey struct {
	PressKey *KeyAction `protobuf:"bytes,13,opt,name=press_key,json=pressKey,proto3,oneof"`
}

type Command_Eval struct {
	Eval *EvalAction `protobuf:"bytes,14,opt,name=eval,proto3,oneof"`
}

type Command_Screenshot struct {
	Screenshot *ScreenshotAction `protobuf:"bytes,15,opt,name=screenshot,proto3,oneof"`
}

type Command_Wait struct {
	Wait *WaitAction `protobuf:"bytes,16,opt,name=wait,proto3,oneof"`
}

type Command_Scroll struct {
	Scroll *ScrollAction `protobuf:"bytes,17,opt,name=scroll,proto3,oneof"`
}

func (*Command_Navigate) isCommand_Action() {}

func (*Command_Click) isCommand_Action() {}

func (*Command_Type) isCommand_Action() {}

func (*Command_PressKey) isCommand_Action() {}

func (*Command_Eval) isCommand_Action() {}

func (*Command_Screenshot) isCommand_Action() {}

func (*Command_Wait) isCommand_Action() {}

func (*Command_Scroll) isCommand_Action() {}

type NavigateAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NavigateAction) Reset() {
	*x = NavigateAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NavigateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NavigateAction) ProtoMessage() {}

func (x *NavigateAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NavigateAction.ProtoReflect.Descriptor instead.
func (*NavigateAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{27}
}

func (x *NavigateAction) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ClickAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickAction) Reset() {
	*x = ClickAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickAction) ProtoMessage() {}

func (x *ClickAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickAction.ProtoReflect.Descriptor instead.
func (*ClickAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{28}
}

func (x *ClickAction) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type TypeAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeAction) Reset() {
	*x = TypeAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeAction) ProtoMessage() {}

func (x *TypeAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeAction.ProtoReflect.Descriptor instead.
func (*TypeAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{29}
}

func (x *TypeAction) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *TypeAction) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type KeyAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyAction) Reset() {
	*x = KeyAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyAction) ProtoMessage() {}

func (x *KeyAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyAction.ProtoReflect.Descriptor instead.
func (*KeyAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{30}
}

func (x *KeyAction) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type EvalAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Script        string                 `protobuf:"bytes,1,opt,name=script,proto3" json:"script,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvalAction) Reset() {
	*x = EvalAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvalAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvalAction) ProtoMessage() {}

func (x *EvalAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvalAction.ProtoReflect.Descriptor instead.
func (*EvalAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{31}
}

func (x *EvalAction) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

type ScreenshotAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullPage      bool                   `protobuf:"varint,1,opt,name=full_page,json=fullPage,proto3" json:"full_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotAction) Reset() {
	*x = ScreenshotAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotAction) ProtoMessage() {}

func (x *ScreenshotAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotAction.ProtoReflect.Descriptor instead.
func (*ScreenshotAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{32}
}

func (x *ScreenshotAction) GetFullPage() bool {
	if x != nil {
		return x.FullPage
	}
	return false
}

type WaitAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Selector      string                 `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WaitAction) Reset() {
	*x = WaitAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WaitAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitAction) ProtoMessage() {}

func (x *WaitAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitAction.ProtoReflect.Descriptor instead.
func (*WaitAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{33}
}

func (x *WaitAction) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *WaitAction) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type ScrollAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScrollAction) Reset() {
	*x = ScrollAction{}
	mi := &file_grpc_proto_scout_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScrollAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScrollAction) ProtoMessage() {}

func (x *ScrollAction) ProtoReflect() protoreflect.Message {
	mi := &file_grpc_proto_scout_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScrollAction.ProtoReflect.Descriptor instead.
func (*ScrollAction) Descriptor() ([]byte, []int) {
	return file_grpc_proto_scout_proto_rawDescGZIP(), []int{34}
}

func (x *ScrollAction) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ScrollAction) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_grpc_proto_scout_proto protoreflect.FileDescriptor

const file_grpc_proto_scout_proto_rawDesc = "" +
	"\n" +
	"\x16grpc/proto/scout.proto\x12\bscout.v1\"\a\n" +
	"\x05Empty\"\xc5\x02\n" +
	"\x14CreateSessionRequest\x12\x1a\n" +
	"\bheadless\x18\x01 \x01(\bR\bheadless\x12\x18\n" +
	"\astealth\x18\x02 \x01(\bR\astealth\x12\x14\n" +
	"\x05proxy\x18\x03 \x01(\tR\x05proxy\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x04 \x01(\tR\tuserAgent\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12\x1f\n" +
	"\vinitial_url\x18\a \x01(\tR\n" +
	"initialUrl\x12\x16\n" +
	"\x06record\x18\b \x01(\bR\x06record\x12!\n" +
	"\fcapture_body\x18\t \x01(\bR\vcaptureBody\x12\x1c\n" +
	"\tmaximized\x18\n" +
	" \x01(\bR\tmaximized\x12\x1a\n" +
	"\bdevtools\x18\v \x01(\bR\bdevtools\"^\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"c\n" +
	"\x0fNavigateRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x1f\n" +
	"\vwait_stable\x18\x03 \x01(\bR\n" +
	"waitStable\"R\n" +
	"\x10NavigateResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"a\n" +
	"\x0eElementRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x14\n" +
	"\x05xpath\x18\x03 \x01(\bR\x05xpath\"}\n" +
	"\vTypeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1f\n" +
	"\vclear_first\x18\x04 \x01(\bR\n" +
	"clearFirst\"`\n" +
	"\rSelectRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"[\n" +
	"\n" +
	"KeyRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1c\n" +
	"\tmodifiers\x18\x03 \x03(\tR\tmodifiers\"k\n" +
	"\x10AttributeRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12\x1c\n" +
	"\tattribute\x18\x03 \x01(\tR\tattribute\"\"\n" +
	"\fTextResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"$\n" +
	"\fBoolResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\"D\n" +
	"\vEvalRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\"&\n" +
	"\fEvalResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\"\x81\x01\n" +
	"\x11ScreenshotRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tfull_page\x18\x02 \x01(\bR\bfullPage\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x18\n" +
	"\aquality\x18\x04 \x01(\x05R\aquality\"@\n" +
	"\x12ScreenshotResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"!\n" +
	"\vPDFResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"T\n" +
	"\x10RecordingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12!\n" +
	"\fcapture_body\x18\x02 \x01(\bR\vcaptureBody\"B\n" +
	"\vHARResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\ventry_count\x18\x02 \x01(\x05R\n" +
	"entryCount\"\xff\x02\n" +
	"\fBrowserEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12B\n" +
	"\frequest_sent\x18\n" +
	" \x01(\v2\x1d.scout.v1.NetworkRequestEventH\x00R\vrequestSent\x12M\n" +
	"\x11response_received\x18\v \x01(\v2\x1e.scout.v1.NetworkResponseEventH\x00R\x10responseReceived\x122\n" +
	"\aconsole\x18\f \x01(\v2\x16.scout.v1.ConsoleEventH\x00R\aconsole\x124\n" +
	"\n" +
	"page_event\x18\r \x01(\v2\x13.scout.v1.PageEventH\x00R\tpageEvent\x12,\n" +
	"\x05error\x18\x0e \x01(\v2\x14.scout.v1.ErrorEventH\x00R\x05errorB\a\n" +
	"\x05event\"\xa2\x02\n" +
	"\x13NetworkRequestEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12D\n" +
	"\aheaders\x18\x04 \x03(\v2*.scout.v1.NetworkRequestEvent.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tpost_data\x18\x05 \x01(\tR\bpostData\x12#\n" +
	"\rresource_type\x18\x06 \x01(\tR\fresourceType\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd6\x02\n" +
	"\x14NetworkResponseEvent\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12\x1f\n" +
	"\vstatus_text\x18\x04 \x01(\tR\n" +
	"statusText\x12E\n" +
	"\aheaders\x18\x05 \x03(\v2+.scout.v1.NetworkResponseEvent.HeadersEntryR\aheaders\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tremote_ip\x18\a \x01(\tR\bremoteIp\x12\x17\n" +
	"\atime_ms\x18\b \x01(\x01R\x06timeMs\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\">\n" +
	"\fConsoleEvent\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\tPageEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04data\x18\x03 \x01(\tR\x04data\">\n" +
	"\n" +
	"ErrorEvent\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\xe0\x03\n" +
	"\aCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x126\n" +
	"\bnavigate\x18\n" +
	" \x01(\v2\x18.scout.v1.NavigateActionH\x00R\bnavigate\x12-\n" +
	"\x05click\x18\v \x01(\v2\x15.scout.v1.ClickActionH\x00R\x05click\x12*\n" +
	"\x04type\x18\f \x01(\v2\x14.scout.v1.TypeActionH\x00R\x04type\x122\n" +
	"\tpress_key\x18\r \x01(\v2\x13.scout.v1.KeyActionH\x00R\bpressKey\x12*\n" +
	"\x04eval\x18\x0e \x01(\v2\x14.scout.v1.EvalActionH\x00R\x04eval\x12<\n" +
	"\n" +
	"screenshot\x18\x0f \x01(\v2\x1a.scout.v1.ScreenshotActionH\x00R\n" +
	"screenshot\x12*\n" +
	"\x04wait\x18\x10 \x01(\v2\x14.scout.v1.WaitActionH\x00R\x04wait\x120\n" +
	"\x06scroll\x18\x11 \x01(\v2\x16.scout.v1.ScrollActionH\x00R\x06scrollB\b\n" +
	"\x06action\"\"\n" +
	"\x0eNavigateAction\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\")\n" +
	"\vClickAction\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\"<\n" +
	"\n" +
	"TypeAction\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\"\x1d\n" +
	"\tKeyAction\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"$\n" +
	"\n" +
	"EvalAction\x12\x16\n" +
	"\x06script\x18\x01 \x01(\tR\x06script\"/\n" +
	"\x10ScreenshotAction\x12\x1b\n" +
	"\tfull_page\x18\x01 \x01(\bR\bfullPage\"G\n" +
	"\n" +
	"WaitAction\x12\x1a\n" +
	"\bselector\x18\x01 \x01(\tR\bselector\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\"*\n" +
	"\fScrollAction\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y2\xab\f\n" +
	"\fScoutService\x12P\n" +
	"\rCreateSession\x12\x1e.scout.v1.CreateSessionRequest\x1a\x1f.scout.v1.CreateSessionResponse\x12;\n" +
	"\x0eDestroySession\x12\x18.scout.v1.SessionRequest\x1a\x0f.scout.v1.Empty\x12A\n" +
	"\bNavigate\x12\x19.scout.v1.NavigateRequest\x1a\x1a.scout.v1.NavigateResponse\x123\n" +
	"\x06Reload\x12\x18.scout.v1.SessionRequest\x1a\x0f.scout.v1.Empty\x123\n" +
	"\x06GoBack\x12\x18.scout.v1.SessionRequest\x1a\x0f.scout.v1.Empty\x126\n" +
	"\tGoForward\x12\x18.scout.v1.SessionRequest\x1a\x0f.scout.v1.Empty\x122\n" +
	"\x05Click\x12\x18.scout.v1.ElementRequest\x1a\x0f.scout.v1.Empty\x128\n" +
	"\vDoubleClick\x12\x18.scout.v1.ElementRequest\x1a\x0f.scout.v1.Empty\x127\n" +
	"\n" +
	"RightClick\x12\x18.scout.v1.ElementRequest\x1a\x0f.scout.v1.Empty\x122\n" +
	"\x05Hover\x12\x18.scout.v1.ElementRequest\x1a\x0f.scout.v1.Empty\x12.\n" +
	"\x04Type\x12\x15.scout.v1.TypeRequest\x1a\x0f.scout.v1.Empty\x128\n" +
	"\fSelectOption\x12\x17.scout.v1.SelectRequest\x1a\x0f.scout.v1.Empty\x121\n" +
	"\bPressKey\x12\x14.scout.v1.KeyRequest\x1a\x0f.scout.v1.Empty\x12;\n" +
	"\aGetText\x12\x18.scout.v1.ElementRequest\x1a\x16.scout.v1.TextResponse\x12B\n" +
	"\fGetAttribute\x12\x1a.scout.v1.AttributeRequest\x1a\x16.scout.v1.TextResponse\x12<\n" +
	"\bGetTitle\x12\x18.scout.v1.SessionRequest\x1a\x16.scout.v1.TextResponse\x12:\n" +
	"\x06GetURL\x12\x18.scout.v1.SessionRequest\x1a\x16.scout.v1.TextResponse\x125\n" +
	"\x04Eval\x12\x15.scout.v1.EvalRequest\x1a\x16.scout.v1.EvalResponse\x12A\n" +
	"\rElementExists\x12\x18.scout.v1.ElementRequest\x1a\x16.scout.v1.BoolResponse\x12G\n" +
	"\n" +
	"Screenshot\x12\x1b.scout.v1.ScreenshotRequest\x1a\x1c.scout.v1.ScreenshotResponse\x126\n" +
	"\x03PDF\x12\x18.scout.v1.SessionRequest\x1a\x15.scout.v1.PDFResponse\x12=\n" +
	"\x0eStartRecording\x12\x1a.scout.v1.RecordingRequest\x1a\x0f.scout.v1.Empty\x12:\n" +
	"\rStopRecording\x12\x18.scout.v1.SessionRequest\x1a\x0f.scout.v1.Empty\x12<\n" +
	"\tExportHAR\x12\x18.scout.v1.SessionRequest\x1a\x15.scout.v1.HARResponse\x12B\n" +
	"\fStreamEvents\x12\x18.scout.v1.SessionRequest\x1a\x16.scout.v1.BrowserEvent0\x01\x12<\n" +
	"\vInteractive\x12\x11.scout.v1.Command\x1a\x16.scout.v1.BrowserEvent(\x010\x01B'Z%github.com/inovacc/scout/grpc/scoutpbb\x06proto3"

var (
	file_grpc_proto_scout_proto_rawDescOnce sync.Once
	file_grpc_proto_scout_proto_rawDescData []byte
)

func file_grpc_proto_scout_proto_rawDescGZIP() []byte {
	file_grpc_proto_scout_proto_rawDescOnce.Do(func() {
		file_grpc_proto_scout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_grpc_proto_scout_proto_rawDesc), len(file_grpc_proto_scout_proto_rawDesc)))
	})
	return file_grpc_proto_scout_proto_rawDescData
}

var file_grpc_proto_scout_proto_msgTypes = make([]protoimpl.MessageInfo, 37)
var file_grpc_proto_scout_proto_goTypes = []any{
	(*Empty)(nil),                 // 0: scout.v1.Empty
	(*CreateSessionRequest)(nil),  // 1: scout.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 2: scout.v1.CreateSessionResponse
	(*SessionRequest)(nil),        // 3: scout.v1.SessionRequest
	(*NavigateRequest)(nil),       // 4: scout.v1.NavigateRequest
	(*NavigateResponse)(nil),      // 5: scout.v1.NavigateResponse
	(*ElementRequest)(nil),        // 6: scout.v1.ElementRequest
	(*TypeRequest)(nil),           // 7: scout.v1.TypeRequest
	(*SelectRequest)(nil),         // 8: scout.v1.SelectRequest
	(*KeyRequest)(nil),            // 9: scout.v1.KeyRequest
	(*AttributeRequest)(nil),      // 10: scout.v1.AttributeRequest
	(*TextResponse)(nil),          // 11: scout.v1.TextResponse
	(*BoolResponse)(nil),          // 12: scout.v1.BoolResponse
	(*EvalRequest)(nil),           // 13: scout.v1.EvalRequest
	(*EvalResponse)(nil),          // 14: scout.v1.EvalResponse
	(*ScreenshotRequest)(nil),     // 15: scout.v1.ScreenshotRequest
	(*ScreenshotResponse)(nil),    // 16: scout.v1.ScreenshotResponse
	(*PDFResponse)(nil),           // 17: scout.v1.PDFResponse
	(*RecordingRequest)(nil),      // 18: scout.v1.RecordingRequest
	(*HARResponse)(nil),           // 19: scout.v1.HARResponse
	(*BrowserEvent)(nil),          // 20: scout.v1.BrowserEvent
	(*NetworkRequestEvent)(nil),   // 21: scout.v1.NetworkRequestEvent
	(*NetworkResponseEvent)(nil),  // 22: scout.v1.NetworkResponseEvent
	(*ConsoleEvent)(nil),          // 23: scout.v1.ConsoleEvent
	(*PageEvent)(nil),             // 24: scout.v1.PageEvent
	(*ErrorEvent)(nil),            // 25: scout.v1.ErrorEvent
	(*Command)(nil),               // 26: scout.v1.Command
	(*NavigateAction)(nil),        // 27: scout.v1.NavigateAction
	(*ClickAction)(nil),           // 28: scout.v1.ClickAction
	(*TypeAction)(nil),            // 29: scout.v1.TypeAction
	(*KeyAction)(nil),             // 30: scout.v1.KeyAction
	(*EvalAction)(nil),            // 31: scout.v1.EvalAction
	(*ScreenshotAction)(nil),      // 32: scout.v1.ScreenshotAction
	(*WaitAction)(nil),            // 33: scout.v1.WaitAction
	(*ScrollAction)(nil),          // 34: scout.v1.ScrollAction
	nil,                           // 35: scout.v1.NetworkRequestEvent.HeadersEntry
	nil,                           // 36: scout.v1.NetworkResponseEvent.HeadersEntry
}
var file_grpc_proto_scout_proto_depIdxs = []int32{
	21, // 0: scout.v1.BrowserEvent.request_sent:type_name -> scout.v1.NetworkRequestEvent
	22, // 1: scout.v1.BrowserEvent.response_received:type_name -> scout.v1.NetworkResponseEvent
	23, // 2: scout.v1.BrowserEvent.console:type_name -> scout.v1.ConsoleEvent
	24, // 3: scout.v1.BrowserEvent.page_event:type_name -> scout.v1.PageEvent
	25, // 4: scout.v1.BrowserEvent.error:type_name -> scout.v1.ErrorEvent
	35, // 5: scout.v1.NetworkRequestEvent.headers:type_name -> scout.v1.NetworkRequestEvent.HeadersEntry
	36, // 6: scout.v1.NetworkResponseEvent.headers:type_name -> scout.v1.NetworkResponseEvent.HeadersEntry
	27, // 7: scout.v1.Command.navigate:type_name -> scout.v1.NavigateAction
	28, // 8: scout.v1.Command.click:type_name -> scout.v1.ClickAction
	29, // 9: scout.v1.Command.type:type_name -> scout.v1.TypeAction
	30, // 10: scout.v1.Command.press_key:type_name -> scout.v1.KeyAction
	31, // 11: scout.v1.Command.eval:type_name -> scout.v1.EvalAction
	32, // 12: scout.v1.Command.screenshot:type_name -> scout.v1.ScreenshotAction
	33, // 13: scout.v1.Command.wait:type_name -> scout.v1.WaitAction
	34, // 14: scout.v1.Command.scroll:type_name -> scout.v1.ScrollAction
	1,  // 15: scout.v1.ScoutService.CreateSession:input_type -> scout.v1.CreateSessionRequest
	3,  // 16: scout.v1.ScoutService.DestroySession:input_type -> scout.v1.SessionRequest
	4,  // 17: scout.v1.ScoutService.Navigate:input_type -> scout.v1.NavigateRequest
	3,  // 18: scout.v1.ScoutService.Reload:input_type -> scout.v1.SessionRequest
	3,  // 19: scout.v1.ScoutService.GoBack:input_type -> scout.v1.SessionRequest
	3,  // 20: scout.v1.ScoutService.GoForward:input_type -> scout.v1.SessionRequest
	6,  // 21: scout.v1.ScoutService.Click:input_type -> scout.v1.ElementRequest
	6,  // 22: scout.v1.ScoutService.DoubleClick:input_type -> scout.v1.ElementRequest
	6,  // 23: scout.v1.ScoutService.RightClick:input_type -> scout.v1.ElementRequest
	6,  // 24: scout.v1.ScoutService.Hover:input_type -> scout.v1.ElementRequest
	7,  // 25: scout.v1.ScoutService.Type:input_type -> scout.v1.TypeRequest
	8,  // 26: scout.v1.ScoutService.SelectOption:input_type -> scout.v1.SelectRequest
	9,  // 27: scout.v1.ScoutService.PressKey:input_type -> scout.v1.KeyRequest
	6,  // 28: scout.v1.ScoutService.GetText:input_type -> scout.v1.ElementRequest
	10, // 29: scout.v1.ScoutService.GetAttribute:input_type -> scout.v1.AttributeRequest
	3,  // 30: scout.v1.ScoutService.GetTitle:input_type -> scout.v1.SessionRequest
	3,  // 31: scout.v1.ScoutService.GetURL:input_type -> scout.v1.SessionRequest
	13, // 32: scout.v1.ScoutService.Eval:input_type -> scout.v1.EvalRequest
	6,  // 33: scout.v1.ScoutService.ElementExists:input_type -> scout.v1.ElementRequest
	15, // 34: scout.v1.ScoutService.Screenshot:input_type -> scout.v1.ScreenshotRequest
	3,  // 35: scout.v1.ScoutService.PDF:input_type -> scout.v1.SessionRequest
	18, // 36: scout.v1.ScoutService.StartRecording:input_type -> scout.v1.RecordingRequest
	3,  // 37: scout.v1.ScoutService.StopRecording:input_type -> scout.v1.SessionRequest
	3,  // 38: scout.v1.ScoutService.ExportHAR:input_type -> scout.v1.SessionRequest
	3,  // 39: scout.v1.ScoutService.StreamEvents:input_type -> scout.v1.SessionRequest
	26, // 40: scout.v1.ScoutService.Interactive:input_type -> scout.v1.Command
	2,  // 41: scout.v1.ScoutService.CreateSession:output_type -> scout.v1.CreateSessionResponse
	0,  // 42: scout.v1.ScoutService.DestroySession:output_type -> scout.v1.Empty
	5,  // 43: scout.v1.ScoutService.Navigate:output_type -> scout.v1.NavigateResponse
	0,  // 44: scout.v1.ScoutService.Reload:output_type -> scout.v1.Empty
	0,  // 45: scout.v1.ScoutService.GoBack:output_type -> scout.v1.Empty
	0,  // 46: scout.v1.ScoutService.GoForward:output_type -> scout.v1.Empty
	0,  // 47: scout.v1.ScoutService.Click:output_type -> scout.v1.Empty
	0,  // 48: scout.v1.ScoutService.DoubleClick:output_type -> scout.v1.Empty
	0,  // 49: scout.v1.ScoutService.RightClick:output_type -> scout.v1.Empty
	0,  // 50: scout.v1.ScoutService.Hover:output_type -> scout.v1.Empty
	0,  // 51: scout.v1.ScoutService.Type:output_type -> scout.v1.Empty
	0,  // 52: scout.v1.ScoutService.SelectOption:output_type -> scout.v1.Empty
	0,  // 53: scout.v1.ScoutService.PressKey:output_type -> scout.v1.Empty
	11, // 54: scout.v1.ScoutService.GetText:output_type -> scout.v1.TextResponse
	11, // 55: scout.v1.ScoutService.GetAttribute:output_type -> scout.v1.TextResponse
	11, // 56: scout.v1.ScoutService.GetTitle:output_type -> scout.v1.TextResponse
	11, // 57: scout.v1.ScoutService.GetURL:output_type -> scout.v1.TextResponse
	14, // 58: scout.v1.ScoutService.Eval:output_type -> scout.v1.EvalResponse
	12, // 59: scout.v1.ScoutService.ElementExists:output_type -> scout.v1.BoolResponse
	16, // 60: scout.v1.ScoutService.Screenshot:output_type -> scout.v1.ScreenshotResponse
	17, // 61: scout.v1.ScoutService.PDF:output_type -> scout.v1.PDFResponse
	0,  // 62: scout.v1.ScoutService.StartRecording:output_type -> scout.v1.Empty
	0,  // 63: scout.v1.ScoutService.StopRecording:output_type -> scout.v1.Empty
	19, // 64: scout.v1.ScoutService.ExportHAR:output_type -> scout.v1.HARResponse
	20, // 65: scout.v1.ScoutService.StreamEvents:output_type -> scout.v1.BrowserEvent
	20, // 66: scout.v1.ScoutService.Interactive:output_type -> scout.v1.BrowserEvent
	41, // [41:67] is the sub-list for method output_type
	15, // [15:41] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_grpc_proto_scout_proto_init() }
func file_grpc_proto_scout_proto_init() {
	if File_grpc_proto_scout_proto != nil {
		return
	}
	file_grpc_proto_scout_proto_msgTypes[20].OneofWrappers = []any{
		(*BrowserEvent_RequestSent)(nil),
		(*BrowserEvent_ResponseReceived)(nil),
		(*BrowserEvent_Console)(nil),
		(*BrowserEvent_PageEvent)(nil),
		(*BrowserEvent_Error)(nil),
	}
	file_grpc_proto_scout_proto_msgTypes[26].OneofWrappers = []any{
		(*Command_Navigate)(nil),
		(*Command_Click)(nil),
		(*Command_Type)(nil),
		(*Command_PressKey)(nil),
		(*Command_Eval)(nil),
		(*Command_Screenshot)(nil),
		(*Command_Wait)(nil),
		(*Command_Scroll)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_grpc_proto_scout_proto_rawDesc), len(file_grpc_proto_scout_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   37,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_grpc_proto_scout_proto_goTypes,
		DependencyIndexes: file_grpc_proto_scout_proto_depIdxs,
		MessageInfos:      file_grpc_proto_scout_proto_msgTypes,
	}.Build()
	File_grpc_proto_scout_proto = out.File
	file_grpc_proto_scout_proto_goTypes = nil
	file_grpc_proto_scout_proto_depIdxs = nil
}
